# build environment
FROM node:13.12.0-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
COPY package-lock.json ./
RUN npm install react-scripts@3.4.1 -g --silent
RUN npm install -g serve
RUN npm i --silent
COPY . ./
RUN npm run build
CMD ["npm", "run", "prod"]